apiVersion: v1
kind: Service
metadata:
  name: nginx-home-service
spec:
  selector:
    app: nginx-home
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort